---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
data:
  MONGO_INITDB_DATABASE: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: UGFzc3dvcmQ=
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_PASSWORD: YWRtaW4=
  MONGO_USERNAME: YWRtaW4=



