apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
spec:
  selector:
    app: mongo
  clusterIP: None   
  ports:   
   - protocol: TCP
     port: 27017
     targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongo
spec:
  replicas: 3
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
        - name: init-mongo
          image: mongo
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
          args:
            - /home/mongodb/scripts/init.sh
          volumeMounts:
            - name: mongo-dir
              mountPath: /home/mongodb
            - name: mongo-key
              mountPath: /home/mongodb/secret
            - name: mongo-init
              mountPath: /home/mongodb/scripts
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          securityContext:
            runAsUser: 999 # Run as Mongo-user  
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_REPLICAS
              value: "3"
          envFrom:
            - secretRef:
                name: mongo-secret
          command:
            - /bin/sh
            - -c
          args:
            - |
              docker-entrypoint.sh mongod \
                --config /home/mongodb/config/mongo.conf 
          workingDir: /home/mongodb         
          volumeMounts:
            - name: mongo-dir
              mountPath: /home/mongodb
            - name: mongo-config
              mountPath: /home/mongodb/config
            - name: mongo-setup
              mountPath: /docker-entrypoint-initdb.d
            - name: mongo-volume
              mountPath: /data/db                        
      volumes:
        - name: mongo-dir
          emptyDir: {}     
        - name: mongo-config
          configMap:
            name: mongo-config
            defaultMode: 0444
        - name: mongo-setup
          configMap:
            name: mongo-setup
            defaultMode: 0555
        - name: mongo-init
          configMap:
            name: mongo-init 
            defaultMode: 0555
        - name: mongo-key
          configMap:
            name: mongo-key 
            defaultMode: 0444                 
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard" # Change the StorageClassName according to your
